migrate dart action part1
Signed-off-by: Daniel Joudat <danieljoudat@gmail.com>

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -12,303 +12,233 @@ jobs:
     name: Generate Clients
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Go 1.
-        uses: actions/setup-go@v2
-        with:
-          go-version: 1.13
-        id: go
 
-      - name: Set up dart latest
-        uses: dart-lang/setup-dart@v1.3
-        with:
-          sdk:  stable
-        id: dart
-
-      - name: Install Protoc
-        uses: arduino/setup-protoc@master
-
-      - name: Check GWT-m3o repo
-        uses: actions/checkout@v2
-        with:
-          repository: 'GWT-M3O-TEST/GWT-m3o'
-          path: m3o
-          ref: ${{ github.ref }}
-
-      - name: Check GWT-services repo
-        uses: actions/checkout@v2
-        with:
-          repository: 'GWT-M3O-TEST/GWT-services'
-          path: services
-
-      - name: Check micro repo
-        uses: actions/checkout@v2
-        with:
-          repository: 'micro/micro'
-          path: 'micro'
-          ref: 'master'
-
-      - name: Check GWT-m3o-go repo
-        uses: actions/checkout@v2
-        with:
-          repository: 'GWT-M3O-TEST/GWT-m3o-go'
-          path: m3o-go
-
-      - name: Check GWT-m3o-dart repo
-        uses: actions/checkout@v2
-        with:
-          repository: 'GWT-M3O-TEST/GWT-m3o-dart'
-          path: m3o-dart
-
-      - name: Enable caching
-        uses: actions/cache@v2
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
-
-      - name: Install protoc gen micro plugin
-        working-directory: micro/cmd/protoc-gen-micro
-        run: |
-          go get -u github.com/golang/protobuf/protoc-gen-go
-          go install
-
-      - name: Install openapi plugin
-        working-directory: m3o/cmd/protoc-gen-openapi
-        run: |
-          go install
-
-      - name: Install generator
-        working-directory: m3o
-        run: |
-          # build the client generator
-          pwd
-          cd cmd/client-gen;
-          go install
-          cd ../../
-          # delete existing cmd directory
-          rm -rf ../services/cmd
-          # copy our command directory in
-          cp -r cmd ../services/
-
-      - name: install prettier
-        working-directory: services
-        run: |
-          sudo npm install -g prettier
-
-      - name: Generate Go, JS and Dart packages
-        working-directory: services
-        if: github.ref == 'refs/heads/main'
-        # env:
-        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-        run: |
-          rm -rf clients examples
-          client-gen dart
-
-      # - name: Generate beta package
-      #   working-directory: services
-      #   if: github.ref == 'refs/heads/beta'
-      #   env:
-      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-      #     IS_BETA: yup
-      #   run: |
-      #     rm -rf clients examples
-      #     client-gen .
-
-      - name: Adjust generated things before pushing
-        working-directory: services
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        run: |
-          # sync the clients to m3o-go/
-          rsync -avz clients/go/ ../m3o-go/
-          # sync the examples to m3o-go/examples
-          rsync -avz examples/go/ ../m3o-go/examples/
-          # remove the .git directory
-          rm -rf ../m3o-go/.git
-          #  move the js examples
-          mkdir clients/ts/examples
-          mv examples/js/* clients/ts/examples/
-          # sync the clients to m3o-dart/
-          rsync -avz clients/dart/* ../m3o-dart/
-          # sync the examples to m3o-dart/example
-          rsync -avz examples/dart/* ../m3o-dart/example/
-
-      - name: Gofmt and test
-        working-directory: m3o-go
-        env:
-          IN_TRAVIS: yes
-        run: |
-          go fmt ./...
-          go test -v ./...
-
-      - name: Install dependencies m3o-dart
-        working-directory: m3o-dart
-        run:  dart pub get
-
-      - name: format m3o-dart
-        working-directory: m3o-dart
-        run:  dart format .
-
-      - name: run generate Freezed m3o-dart
-        working-directory: m3o-dart
-        run:  dart pub run build_runner build --delete-conflicting-outputs
-
-      - name: update dart version number
-        working-directory: m3o-dart
-        run: |
-          oldver=$(cat pubspec.yaml | grep version | head -1) 
-          patch=$(echo $oldver | awk -F. '{ print $3}') 
-          newpatch=$(($patch+1)) 
-          seg1=$(echo $oldver | awk -F. '{ print $1}') 
-          seg2=$(echo $oldver | awk -F. '{ print $2}') 
-          newver="$seg1.$seg2.$newpatch" 
-          sed -i "s/$oldver/$newver/" pubspec.yaml
-          echo "##[set-output name=newver;]$(echo $newver)"
-        id: dart_new_version
-
-      - name: house cleaning remove unnecessary files/folders
-        working-directory: m3o-dart
-        run: |
-          rm -rf .dart_tool .git .gitignore .packages pubspec.lock
-          
-      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
-      - name: Extract branch name
-        shell: bash
-        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
-          
-      - name: Push Go files
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'm3o-go/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-go'
-          destination_branch: ${{ steps.extract_branch.outputs.branch }}
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
-          
-      - name: Push JS files
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'services/clients/ts/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-js'
-          destination_branch: ${{ steps.extract_branch.outputs.branch }}
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
-
-      - name: Push Dart clients
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'm3o-dart/lib/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-dart'
-          destination_branch: ${{ steps.extract_branch.outputs.branch }}
-          destination_folder: 'lib/'
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
-
-      - name: Push Dart examples
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'm3o-dart/example/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-dart'
-          destination_branch: ${{ steps.extract_branch.outputs.branch }}
-          destination_folder: 'example/'
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
-
-      - name: Push Dart pubspec and changelog
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'm3o-dart/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-dart'
-          destination_branch: ${{ steps.extract_branch.outputs.branch }}
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
-      
-      - name: Push shell files
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'services/examples/curl/'
-          destination_repo: 'GWT-M3O-TEST/GWT-m3o-sh'
-          destination_folder: 'examples'
-          destination_branch: '${{ steps.extract_branch.outputs.branch }}'
-          git_server: 'github.com'
-          user_email:  'danieljoudat@gmail.com'
-          user_name: 'lambdaR'
-          use_rsync: true
-          commit_message: 'Commit from GWT-M3O_TEST/GWT-m3o action'
-
-      - name: Trigger M3O-Dart Publish Action.
+      - name: Trigger M3O-Dart
         run: |
           curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-dart/dispatches -d '{"event_type":"publish_dart"}'
         env:
           GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
 
-      # - name: install postman converter
+      # - name: Set up Go 1.13
+      #   uses: actions/setup-go@v2
+      #   with:
+      #     go-version: 1.13
+      #   id: go
+
+      
+
+      # - name: Install Protoc
+      #   uses: arduino/setup-protoc@master
+
+      # - name: Check GWT-m3o repo
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: 'GWT-M3O-TEST/GWT-m3o'
+      #     path: m3o
+      #     ref: ${{ github.ref }}
+
+      # - name: Check GWT-services repo
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: 'GWT-M3O-TEST/GWT-services'
+      #     path: services
+
+      # - name: Check micro repo
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: 'micro/micro'
+      #     path: 'micro'
+      #     ref: 'master'
+
+      # - name: Check GWT-m3o-go repo
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: 'GWT-M3O-TEST/GWT-m3o-go'
+      #     path: m3o-go
+
+      # - name: Check GWT-m3o-dart repo
+      #   uses: actions/checkout@v2
+      #   with:
+      #     repository: 'GWT-M3O-TEST/GWT-m3o-dart'
+      #     path: m3o-dart
+
+      # - name: Enable caching
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: ~/go/pkg/mod
+      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-go-
+
+      # - name: Install protoc gen micro plugin
+      #   working-directory: micro/cmd/protoc-gen-micro
+      #   run: |
+      #     go get -u github.com/golang/protobuf/protoc-gen-go
+      #     go install
+
+      # - name: Install openapi plugin
+      #   working-directory: m3o/cmd/protoc-gen-openapi
+      #   run: |
+      #     go install
+
+      # - name: Install generator
+      #   working-directory: m3o
+      #   run: |
+      #     # build the client generator
+      #     pwd
+      #     cd cmd/client-gen;
+      #     go install
+      #     cd ../../
+      #     # delete existing cmd directory
+      #     rm -rf ../services/cmd
+      #     # copy our command directory in
+      #     cp -r cmd ../services/
+
+      # - name: install prettier
       #   working-directory: services
       #   run: |
-      #     sudo npm install -g openapi-to-postmanv2
-      #     openapi2postmanv2 -h
+      #     sudo npm install -g prettier
 
-      # - name: Generate openapi spec and publish the api
+      # - name: Generate Go, JS and Dart packages
       #   working-directory: services
       #   if: github.ref == 'refs/heads/main'
+      #   # env:
+      #   #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
       #   run: |
-      #     go run cmd/api-publisher/main.go .
+      #     rm -rf clients examples
+      #     client-gen dart
+
+      # # - name: Generate beta package
+      # #   working-directory: services
+      # #   if: github.ref == 'refs/heads/beta'
+      # #   env:
+      # #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+      # #     IS_BETA: yup
+      # #   run: |
+      # #     rm -rf clients examples
+      # #     client-gen .
+
+      # - name: Adjust generated things before pushing
+      #   working-directory: services
+      #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
+      #   run: |
+      #     # sync the clients to m3o-go/
+      #     rsync -avz clients/go/ ../m3o-go/
+      #     # sync the examples to m3o-go/examples
+      #     rsync -avz examples/go/ ../m3o-go/examples/
+      #     # remove the .git directory
+      #     rm -rf ../m3o-go/.git
+      #     #  move the js examples
+      #     mkdir clients/ts/examples
+      #     mv examples/js/* clients/ts/examples/
+      #     # sync the clients to m3o-dart/
+      #     rsync -avz clients/dart/* ../m3o-dart/
+      #     # sync the examples to m3o-dart/example
+      #     rsync -avz examples/dart/* ../m3o-dart/example/
+
+      # - name: Gofmt and test
+      #   working-directory: m3o-go
       #   env:
-      #     MICRO_ADMIN_TOKEN: ${{ secrets.MICRO_ADMIN_TOKEN }}
-
-      # - name: publish npm clients
-      #   working-directory: services
-      #   if: github.ref == 'refs/heads/main'
+      #     IN_TRAVIS: yes
       #   run: |
-      #     git status
-      #     cd clients/ts;
-      #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
-      #     npm install
-      #     npm run build
-      #     npm publish --access public
+      #     go fmt ./...
+      #     go test -v ./...
 
-      # - name: publish npm beta clients
-      #   working-directory: services
-      #   if: github.ref == 'refs/heads/beta'
-      #   run: |
-      #     git status
-      #     cd clients/ts;
-      #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
-      #     npm install
-      #     npm run build
-      #     npm publish --access public --tag beta
+      # - name: Install dependencies m3o-dart
+      #   working-directory: m3o-dart
+      #   run:  dart pub get
+
+      
+
+      
+          
+      # # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
+      # - name: Extract branch name
+      #   shell: bash
+      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+      #   id: extract_branch
+          
+      # - name: Push Go files
+      #   uses: dmnemec/copy_file_to_another_repo_action@main
+      #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
+      #   env:
+      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      #   with:
+      #     source_file: 'm3o-go/'
+      #     destination_repo: 'GWT-M3O-TEST/GWT-m3o-go'
+      #     destination_branch: ${{ steps.extract_branch.outputs.branch }}
+      #     git_server: 'github.com'
+      #     user_email:  'danieljoudat@gmail.com'
+      #     user_name: 'lambdaR'
+      #     use_rsync: true
+      #     commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
+          
+      # - name: Push JS files
+      #   uses: dmnemec/copy_file_to_another_repo_action@main
+      #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
+      #   env:
+      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      #   with:
+      #     source_file: 'services/clients/ts/'
+      #     destination_repo: 'GWT-M3O-TEST/GWT-m3o-js'
+      #     destination_branch: ${{ steps.extract_branch.outputs.branch }}
+      #     git_server: 'github.com'
+      #     user_email:  'danieljoudat@gmail.com'
+      #     user_name: 'lambdaR'
+      #     use_rsync: true
+      #     commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'
+
+      
+      
+      # - name: Push shell files
+      #   uses: dmnemec/copy_file_to_another_repo_action@main
+      #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
+      #   env:
+      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      #   with:
+      #     source_file: 'services/examples/curl/'
+      #     destination_repo: 'GWT-M3O-TEST/GWT-m3o-sh'
+      #     destination_folder: 'examples'
+      #     destination_branch: '${{ steps.extract_branch.outputs.branch }}'
+      #     git_server: 'github.com'
+      #     user_email:  'danieljoudat@gmail.com'
+      #     user_name: 'lambdaR'
+      #     use_rsync: true
+      #     commit_message: 'Commit from GWT-M3O_TEST/GWT-m3o action'
+
+      # # - name: install postman converter
+      # #   working-directory: services
+      # #   run: |
+      # #     sudo npm install -g openapi-to-postmanv2
+      # #     openapi2postmanv2 -h
+
+      # # - name: Generate openapi spec and publish the api
+      # #   working-directory: services
+      # #   if: github.ref == 'refs/heads/main'
+      # #   run: |
+      # #     go run cmd/api-publisher/main.go .
+      # #   env:
+      # #     MICRO_ADMIN_TOKEN: ${{ secrets.MICRO_ADMIN_TOKEN }}
+
+      # # - name: publish npm clients
+      # #   working-directory: services
+      # #   if: github.ref == 'refs/heads/main'
+      # #   run: |
+      # #     git status
+      # #     cd clients/ts;
+      # #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
+      # #     npm install
+      # #     npm run build
+      # #     npm publish --access public
+
+      # # - name: publish npm beta clients
+      # #   working-directory: services
+      # #   if: github.ref == 'refs/heads/beta'
+      # #   run: |
+      # #     git status
+      # #     cd clients/ts;
+      # #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
+      # #     npm install
+      # #     npm run build
+      # #     npm publish --access public --tag beta
 
