Initial commit

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -30,7 +30,7 @@ jobs:
       - name: Check services repo
         uses: actions/checkout@v2
         with:
-          repository: 'micro/services'
+          repository: 'lambdaR/GWT-services'
           path: services
 
       - name: Check micro repo
@@ -43,7 +43,7 @@ jobs:
       - name: Check m3o-go repo
         uses: actions/checkout@v2
         with:
-          repository: 'm3o/m3o-go'
+          repository: 'lambdaR/GWT-m3o-go'
           path: m3o-go
 
       - name: Enable caching
@@ -86,21 +86,21 @@ jobs:
       - name: Generate Go and JS packages
         working-directory: services
         if: github.ref == 'refs/heads/main'
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+        # env:
+        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         run: |
           rm -rf clients examples
           client-gen .
 
-      - name: Generate beta package
-        working-directory: services
-        if: github.ref == 'refs/heads/beta'
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          IS_BETA: yup
-        run: |
-          rm -rf clients examples
-          client-gen .
+      # - name: Generate beta package
+      #   working-directory: services
+      #   if: github.ref == 'refs/heads/beta'
+      #   env:
+      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+      #     IS_BETA: yup
+      #   run: |
+      #     rm -rf clients examples
+      #     client-gen .
 
       - name: Adjust generated things before pushing
         working-directory: services
@@ -137,12 +137,12 @@ jobs:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
         with:
           source_file: 'm3o-go/'
-          destination_repo: 'm3o/m3o-go'
+          destination_repo: 'lambdaR/GWT-m3o-go'
           destination_branch: ${{ steps.extract_branch.outputs.branch }}
           github_server: 'github.com'
-          user_name: 'm3o-actions'
+          user_name: 'GWT-m3o-actions'
           use_rsync: true
-          commit_message: 'Commit from m3o/m3o action'
+          commit_message: 'Commit from lambdaR/GWT-m3o action'
 
       - name: Push JS files
         uses: dmnemec/copy_file_to_another_repo_action@main
@@ -151,61 +151,61 @@ jobs:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
         with:
           source_file: 'services/clients/ts/'
-          destination_repo: 'm3o/m3o-js'
+          destination_repo: 'lambdaR/GWT-m3o-js'
           destination_branch: ${{ steps.extract_branch.outputs.branch }}
           github_server: 'github.com'
-          user_name: 'm3o-actions'
+          user_name: 'GWT-m3o-actions'
           use_rsync: true
-          commit_message: 'Commit from m3o/m3o action'
+          commit_message: 'Commit from lambdaR/GWT-m3o action'
 
-      - name: Push shell files
-        uses: dmnemec/copy_file_to_another_repo_action@main
-        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-        with:
-          source_file: 'services/examples/curl/'
-          destination_repo: 'm3o/m3o-sh'
-          destination_folder: 'examples'
-          destination_branch: '${{ steps.extract_branch.outputs.branch }}'
-          github_server: 'github.com'
-          user_name: 'm3o-actions'
-          use_rsync: true
-          commit_message: 'Commit from m3o/m3o action'
+      # - name: Push shell files
+      #   uses: dmnemec/copy_file_to_another_repo_action@main
+      #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
+      #   env:
+      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      #   with:
+      #     source_file: 'services/examples/curl/'
+      #     destination_repo: 'm3o/m3o-sh'
+      #     destination_folder: 'examples'
+      #     destination_branch: '${{ steps.extract_branch.outputs.branch }}'
+      #     github_server: 'github.com'
+      #     user_name: 'm3o-actions'
+      #     use_rsync: true
+      #     commit_message: 'Commit from m3o/m3o action'
 
-      - name: install postman converter
-        working-directory: services
-        run: |
-          sudo npm install -g openapi-to-postmanv2
-          openapi2postmanv2 -h
+      # - name: install postman converter
+      #   working-directory: services
+      #   run: |
+      #     sudo npm install -g openapi-to-postmanv2
+      #     openapi2postmanv2 -h
 
-      - name: Generate openapi spec and publish the api
-        working-directory: services
-        if: github.ref == 'refs/heads/main'
-        run: |
-          go run cmd/api-publisher/main.go .
-        env:
-          MICRO_ADMIN_TOKEN: ${{ secrets.MICRO_ADMIN_TOKEN }}
+      # - name: Generate openapi spec and publish the api
+      #   working-directory: services
+      #   if: github.ref == 'refs/heads/main'
+      #   run: |
+      #     go run cmd/api-publisher/main.go .
+      #   env:
+      #     MICRO_ADMIN_TOKEN: ${{ secrets.MICRO_ADMIN_TOKEN }}
 
-      - name: publish npm clients
-        working-directory: services
-        if: github.ref == 'refs/heads/main'
-        run: |
-          git status
-          cd clients/ts;
-          if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
-          npm install
-          npm run build
-          npm publish --access public
+      # - name: publish npm clients
+      #   working-directory: services
+      #   if: github.ref == 'refs/heads/main'
+      #   run: |
+      #     git status
+      #     cd clients/ts;
+      #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
+      #     npm install
+      #     npm run build
+      #     npm publish --access public
 
-      - name: publish npm beta clients
-        working-directory: services
-        if: github.ref == 'refs/heads/beta'
-        run: |
-          git status
-          cd clients/ts;
-          if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
-          npm install
-          npm run build
-          npm publish --access public --tag beta
+      # - name: publish npm beta clients
+      #   working-directory: services
+      #   if: github.ref == 'refs/heads/beta'
+      #   run: |
+      #     git status
+      #     cd clients/ts;
+      #     if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
+      #     npm install
+      #     npm run build
+      #     npm publish --access public --tag beta
 
